image: python:3.9

stages:
  - lint
  - test
  - deploy

cache:
  paths:
    - .cache/pip

lint-job:
  stage: lint
  script:
    - pip install flake8
    - flake8 hello-devops/

test-job:
  stage: test
  script:
    - pip install -r hello-devops/requirements.txt
    - python -m pytest hello-devops/

deploy-job:
  stage: deploy
  script:
    - echo "Deploying to staging..."
  when: manual

post_deploy-validation:
  stage: post_deploy
  script:
    - curl http://localhost:5000 && echo "App is up!"
